/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const CompanyInfo = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBook' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'editBook' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getBio' : IDL.Func([], [IDL.Text], ['query']),
  'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
  'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
  'updateBio' : IDL.Func([IDL.Text], [], []),
  'updateCompanyInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const CompanyInfo = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addBook' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'editBook' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getBio' : IDL.Func([], [IDL.Text], ['query']),
    'getBook' : IDL.Func([IDL.Nat], [IDL.Opt(Book)], ['query']),
    'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
    'updateBio' : IDL.Func([IDL.Text], [], []),
    'updateCompanyInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };